config/routes.rb
Rails.application.routes.draw do
  post 'tweets/new' => 'tweets#new' 
  resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
    
  end
  
  root 'tweets#index'
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :content, presence: true, length:{ in: 1..255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :set_tweet, only: [:edit, :update, :destroy]
    
  def index
      @tweets = Tweet.all
      if params[:back]
        @tweet = Tweet.new(tweets_params)
      else
        @tweet = Tweet.new
      end
  end

  def new
      if params[:back]
        @tweet = Tweet.new(tweets_params)
      else
        @tweet = Tweet.new
      end
  end
  
  def confirm
      @tweet = Tweet.new(tweets_params)
      render :new if @tweet.invalid?
  end

  def create
      @tweet =Tweet.new(tweets_params)
      if @tweet.save
        redirect_to tweets_path, notice: "ツイートしました！"
      else
        render :new
      end
  end
  
  def edit 
  end
  
  def update
    if
     @tweet.update(tweets_params)
     redirect_to tweets_path, notice: "ツイートを更新しました！"
   else
      render :edit
    end
  end
  
  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "ツイートを削除しました！"
  end
  
  
  
  private
    def tweets_params
      params.require(:tweet).permit(:content)
    end
    
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def choose_new_or_edit
        if action_name == 'index' || action_name == 'confirm' || action_name == 'new'
            confirm_tweets_path
        elsif action_name == 'edit'
            tweet_path
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
    
      <%= link_to "ホーム", root_path, class: "navbar-brand" %>
      <%= link_to "通知", root_path, class: "navbar-brand" %>
      <%= link_to "メッセージ", root_path, class: "navbar-brand" %>
      
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
  </div><!-- /.container-fluid -->
</nav>
</header>

<%= yield %>

      <footer>
            <p>twitter</p>
      </footer>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet, url: choose_new_or_edit ) do |f| %>
  <% if @tweet.errors.any? %>
     <div id="errors_explaination">
       <p><%= @tweet.errors.count %>件のエラーが発生しました。</p>
         <ul>
           <% @tweet.errors.full_messages.each do |message| %>
           <li><%= message %></li>
           <% end %>
         </ul>
     </div>
  <% end %>
       
  <br>
  <div id="submit">
  <%= f.label :ツイートする %>
  <br>
  <%= f.text_area :content, class: 'form-control' %>
  <br>
  <%= f.submit "送　信", class: 'btn btn-block submit'%>
  </div>
<% end %>

app/views/tweets/confirm.html.erb
<div class="container">
<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<p>この内容で、ツイートします</p>

<%= form_for(@tweet) do |f| %>

<%= f.hidden_field :content %>
<%= @tweet.content %>
<br>
<%= f.submit "送 信", class: 'btn btn-block submit'%>
<% end %>

<%= form_for(@tweet, url: tweets_new_path, method: 'post') do |f| %>
<%= f.hidden_field :content %>
<%= f.submit "もどる", name: 'back', class: 'btn btn-block back'%>
<% end %>


   </div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

        <p>ツイート編集</p>
        <%= render 'form' %>
    </div>   
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-2  col-sm-10">
  </div>
  <div class="wrapper col-md-8  　col-sm-10">

  <p><%= notice %></p>


  <%= render 'form' %>
  
   <div id="list">
      <h1>ツイート一覧</h1>

      <% @tweets.each do |tweet| %>
      <div class="row">
        <p><%= tweet.content %></p>
        <%= link_to "編集", edit_tweet_path(tweet.id), class: 'btn btn-default btn-sm edit'%>
        <%= link_to "削除", tweet_path(tweet), method: :delete, data: { confirm: '本当に削除していいですか？' },class: 'btn btn-default btn-sm btn delete' %>
      </div>
      <% end %>
   </div> 
  </div>
 
  </div>
</div>
<div id="gototop">
  <div id="gototop2"></div>
</div>

app/views/tweets/new.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
       
       <%= render 'form' %>
       
    </div>   
</div>